# Generated by Django 4.0.5 on 2022-08-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_pessoa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='pessoa.pessoa'),
        ),
    ]
